# Generated by Django 5.0.3 on 2024-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buyer_address_buyer_city_buyer_country_buyer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='menus',
            field=models.ManyToManyField(through='app.RecipeMenu', to='app.menu'),
        ),
    ]
